version: "3"
services:
  app:
    image: node:20-alpine
    restart: always
    volumes:
      - ./server:/app
    working_dir: /app
    ports:
      - 3002:3002
    environment:
      PORT: 3002
      REDIS_URL: redis://storage
    command: sh -c "if ! [ -d ./node_modules ];then npm install;fi;\
      npm run start:dev"

  frontend:
    image: node:20-alpine
    restart: always
    volumes:
      - ./frontend:/app
    working_dir: /app
    ports:
      - 50012:50012
    environment:
      PORT: 50012
      APP_URL: http://localhost
      APP_PORT: 3002
    command: sh -c "if ! [ -d ./node_modules ];then npm install;fi;\
      npm run start"
    depends_on:
      - app
