version: "3"
services:
  app:
    image: node:22-alpine
    restart: always
    volumes:
      - ./server:/app
    working_dir: /app
    ports:
      - 3002:3002
    command: sh -c "npm install && npm run start:dev"
    depends_on:
      - mongo

  frontend:
    image: node:22-alpine
    restart: always
    volumes:
      - ./frontend:/app
    working_dir: /app
    ports:
      - 50012:50012
    command: sh -c "npm install && npm run start"
    depends_on:
      - app

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - ./db_data/mongo:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
